"""Offline helpers for the 0816:2475 / MCU-951 configuration protocol.

This module deliberately does not import hid or open a device.  It only builds
reports so that their bytes can be reviewed before any future write operation.
"""

from __future__ import annotations

REPORT_SIZE = 65  # report ID byte + 64-byte HID payload
COMMAND_DEVICE = 0x06
COMMAND_SET_KEY = 0x10  # key-mapping subcommand inside command 0x06
KEY_COUNT = 25  # 16 keys + 3 encoder actions per encoder


def build_set_key_info_report(
    key_index: int,
    *,
    layer: int = 0,
    key_type: int = 0,
    code1: int = 0,
    code2: int = 0,
    code3: int = 0,
) -> bytes:
    """Build one key-mapping report without sending it anywhere.

    The web configurator stores four bytes per control:
    ``type, code1, code2, code3``.  The first 16 indices are the grid;
    the device profile assigns indices 16-18 to knob 1, 19-21 to knob 2,
    and 22-24 to knob 3.  Within each group, the profile places press,
    counterclockwise, and clockwise at offsets 0, 1, and 2 respectively.

    Parameters
    ----------
    key_index : int
        Storage index from 0 through 24.
    layer : int, default=0
        Device layer number, encoded as one byte.
    key_type : int, default=0
        Device-specific action type.
    code1, code2, code3 : int, default=0
        The three action-code bytes stored after ``key_type``.

    Returns
    -------
    bytes
        A 65-byte hidapi-style buffer containing the report ID and payload.

    Raises
    ------
    ValueError
        If the index, layer, type, or code values do not fit the protocol.
    """

    if not 0 <= key_index < KEY_COUNT:
        raise ValueError(f"key_index must be 0..{KEY_COUNT - 1}")
    if not 0 <= layer <= 255:
        raise ValueError("layer must be one byte")
    values = (key_type, code1, code2, code3)
    if any(not 0 <= value <= 255 for value in values):
        raise ValueError("key type and codes must each be one byte")

    payload = bytearray(63)
    payload[0] = COMMAND_SET_KEY
    payload[1] = 7
    offset = 4 * key_index
    payload[2] = offset & 0xFF
    payload[3] = (offset >> 8) & 0xFF
    payload[5] = layer
    payload[7:11] = bytes(values)

    # WebHID's sendReport(0, payload) receives the report without the
    # report-ID byte; this is the complete 65-byte hidapi-style buffer.
    return bytes([0, COMMAND_DEVICE]) + bytes(payload)


def describe_report(report: bytes) -> str:
    """Return a compact description useful for reviewing generated bytes.

    Parameters
    ----------
    report : bytes
        A complete 65-byte hidapi-style report buffer.

    Returns
    -------
    str
        A human-readable summary of the report fields.

    Raises
    ------
    ValueError
        If ``report`` is not exactly 65 bytes long.
    """

    if len(report) != REPORT_SIZE:
        raise ValueError(f"expected {REPORT_SIZE} bytes, got {len(report)}")
    payload = report[2:]
    offset = payload[2] | (payload[3] << 8)
    values = tuple(payload[7:11])
    return (
        f"report_id={report[0]} command=0x{report[1]:02X} "
        f"subcommand=0x{payload[0]:02X} offset={offset} "
        f"layer={payload[5]} values={values}"
    )
